---
# tasks file for ansible_role_epel-release

- name: "EPEL | {{ epel-release_state.state }}"
  yum:
    name: epel-release
    state: "{{ epel-release_state }}"
  tags:
    - install
    - epel-release
    - uninstall
