---
# tasks file for ansible_role_epel_release

- name: "EPEL | {{ epel_release_state }}"
  yum:
    name: epel-release
    state: "{{ epel_release_state }}"
  tags:
    - install
    - epel_release
    - uninstall
